/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js.
// It only exists to help TypeScript understand Next.js types.

